sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 121.199.66.74
    port: 3306
    database: sky_take_out
    username: snow
    password: 820820328Zz
  redis:
    host: 121.199.66.74
    port: 6379
    password: 820820328Zz
    database: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQZigmvdi1vgesVUArc
    access-key-secret: awCz9KreFszpRSuDbIzd2ig6UwnXR3
    bucket-name: snowcrane
  wechat:
    appid: wxe8b49e02e5daac17
    secret: 55a2c256fc9a60eb64fb107c93d4e01c
